// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-live-channels.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^4.6.5";

// src/data/channels.ts
var EMBED_BASE = "https://ww5.embedtv.lat";
var IMG_BASE = "https://embedtv.lat/assets/images";
var categories = [
  { id: "all", name: "Todos", emoji: "\u{1F4FA}" },
  { id: "esportes", name: "Esportes", emoji: "\u26BD" },
  { id: "filmes", name: "Filmes e S\xE9ries", emoji: "\u{1F3AC}" },
  { id: "noticias", name: "Not\xEDcias", emoji: "\u{1F4F0}" },
  { id: "abertos", name: "Abertos", emoji: "\u{1F4E1}" },
  { id: "infantil", name: "Infantil", emoji: "\u{1F9F8}" },
  { id: "documentarios", name: "Document\xE1rios", emoji: "\u{1F30D}" },
  { id: "variedades", name: "Variedades", emoji: "\u{1F3AD}" },
  { id: "bbb", name: "BBB 2026", emoji: "\u{1F3E0}" }
];
function ch(id, name, img, category) {
  return { id, name, logo: `${IMG_BASE}/${img}.png`, category, embed: `${EMBED_BASE}/${id}` };
}
var channels = [
  // === BBB ===
  ch("bbb", "BBB - Mosaico", "bbb", "bbb"),
  ch("bbb1", "BBB - 1", "bbb", "bbb"),
  ch("bbb2", "BBB - 2", "bbb", "bbb"),
  ch("bbb3", "BBB - 3", "bbb", "bbb"),
  ch("bbb4", "BBB - 4", "bbb", "bbb"),
  ch("bbb5", "BBB - 5", "bbb", "bbb"),
  ch("bbb6", "BBB - 6", "bbb", "bbb"),
  ch("bbb7", "BBB - 7", "bbb", "bbb"),
  ch("bbb8", "BBB - 8", "bbb", "bbb"),
  ch("bbb9", "BBB - 9", "bbb", "bbb"),
  ch("bbb10", "BBB - 10", "bbb", "bbb"),
  // === ESPORTES ===
  ch("bandsports", "Band Sports", "bandsports", "esportes"),
  ch("caze1", "Caz\xE9TV 1", "cazetv", "esportes"),
  ch("caze2", "Caz\xE9TV 2", "cazetv", "esportes"),
  ch("caze3", "Caz\xE9TV 3", "cazetv", "esportes"),
  ch("combate", "Combate", "combate", "esportes"),
  ch("disneyplus1", "Disney Plus 1", "disneyplus", "esportes"),
  ch("disneyplus2", "Disney Plus 2", "disneyplus", "esportes"),
  ch("disneyplus3", "Disney Plus 3", "disneyplus", "esportes"),
  ch("espn", "ESPN", "espn", "esportes"),
  ch("espn2", "ESPN 2", "espn2", "esportes"),
  ch("espn3", "ESPN 3", "espn3", "esportes"),
  ch("espn4", "ESPN 4", "espn4", "esportes"),
  ch("espn5", "ESPN 5", "espn5", "esportes"),
  ch("espn6", "ESPN 6", "espn6", "esportes"),
  ch("max1", "Max 1", "max", "esportes"),
  ch("max2", "Max 2", "max", "esportes"),
  ch("max3", "Max 3", "max", "esportes"),
  ch("paramountplus", "Paramount Plus", "paramountplus", "esportes"),
  ch("paramountplus2", "Paramount Plus 2", "paramountplus", "esportes"),
  ch("premiere", "Premiere 1", "premiere", "esportes"),
  ch("premiere2", "Premiere 2", "premiere", "esportes"),
  ch("premiere3", "Premiere 3", "premiere", "esportes"),
  ch("premiere4", "Premiere 4", "premiere", "esportes"),
  ch("premiere5", "Premiere 5", "premiere", "esportes"),
  ch("premiere6", "Premiere 6", "premiere", "esportes"),
  ch("premiere7", "Premiere 7", "premiere", "esportes"),
  ch("premiere8", "Premiere 8", "premiere", "esportes"),
  ch("primevideo", "Prime Video", "primevideo", "esportes"),
  ch("primevideo2", "Prime Video 2", "primevideo", "esportes"),
  ch("sportv", "SporTV", "sportv", "esportes"),
  ch("sportv2", "SporTV 2", "sportv2", "esportes"),
  ch("sportv3", "SporTV 3", "sportv3", "esportes"),
  ch("sportv4", "SporTV 4", "sportv4", "esportes"),
  ch("ufcfightpass", "UFC Fight Pass", "ufcfightpass", "esportes"),
  // === INFANTIL ===
  ch("24h_dragonball", "24H Dragon Ball Z", "24h", "infantil"),
  ch("24h_odeiachris", "24H Todo Mundo Odeia o Cris", "24h", "infantil"),
  ch("24h_simpsons", "24H Os Simpsons", "24h", "infantil"),
  ch("cartoonito", "Cartoonito", "cartoonito", "infantil"),
  ch("cartoonnetwork", "Cartoon Network", "cartoonnetwork", "infantil"),
  ch("discoverykids", "Discovery Kids", "discoverykids", "infantil"),
  ch("gloob", "Gloob", "gloob", "infantil"),
  ch("nickelodeon", "Nickelodeon", "nickelodeon", "infantil"),
  ch("nickjunior", "Nick Junior", "nickjr", "infantil"),
  // === DOCUMENTÁRIOS ===
  ch("animalplanet", "Animal Planet", "animalplanet", "documentarios"),
  ch("discoverychannel", "Discovery Channel", "discoverychannel", "documentarios"),
  ch("discoveryhh", "Discovery H&H", "discoveryhh", "documentarios"),
  ch("discoveryid", "Discovery ID", "discoverychannel", "documentarios"),
  ch("discoveryscience", "Discovery Science", "discoveryscience", "documentarios"),
  ch("discoverytheather", "Discovery Theater", "discoverytheater", "documentarios"),
  ch("discoveryturbo", "Discovery Turbo", "discoveryturbo", "documentarios"),
  ch("discoveryword", "Discovery World", "discoveryworld", "documentarios"),
  ch("fish", "Fish TV", "fishtv", "documentarios"),
  ch("history", "History", "history", "documentarios"),
  ch("history2", "History 2", "history2", "documentarios"),
  // === FILMES E SÉRIES ===
  ch("adultswim", "Adult Swim", "adultswim", "filmes"),
  ch("ae", "A&E", "ae", "filmes"),
  ch("axn", "AXN", "axn", "filmes"),
  ch("cinemax", "Cinemax", "cinemax", "filmes"),
  ch("comedycentral", "Comedy Central", "comedycentral", "filmes"),
  ch("gnt", "GNT", "gnt", "filmes"),
  ch("hbo", "HBO", "hbo", "filmes"),
  ch("hbo2", "HBO 2", "hbo2", "filmes"),
  ch("hbofamily", "HBO Family", "hbofamily", "filmes"),
  ch("hbomundi", "HBO Mundi", "hbomundi", "filmes"),
  ch("hboplus", "HBO Plus", "hboplus", "filmes"),
  ch("hbopop", "HBO POP", "hbopop", "filmes"),
  ch("hboxtreme", "HBO Xtreme", "hboxtreme", "filmes"),
  ch("hgtv", "HGTV", "hgtv", "filmes"),
  ch("megapix", "Megapix", "megapix", "filmes"),
  ch("off", "OFF", "off", "filmes"),
  ch("paramountchannel", "Paramount", "paramountchannel", "filmes"),
  ch("sonychannel", "Sony Channel", "sonychannel", "filmes"),
  ch("space", "Space", "space", "filmes"),
  ch("starchannel", "Star Channel", "starchannel", "filmes"),
  ch("studiouniversal", "Studio Universal", "studiouniversal", "filmes"),
  ch("tcm", "TCM", "tcm", "filmes"),
  ch("telecineaction", "Telecine Action", "telecineaction", "filmes"),
  ch("telecinecult", "Telecine Cult", "telecinecult", "filmes"),
  ch("telecinefun", "Telecine Fun", "telecinefun", "filmes"),
  ch("telecinepipoca", "Telecine Pipoca", "telecinepipoca", "filmes"),
  ch("telecinepremium", "Telecine Premium", "telecinepremium", "filmes"),
  ch("telecinetouch", "Telecine Touch", "telecinetouch", "filmes"),
  ch("tlc", "TLC", "tlc", "filmes"),
  ch("tnt", "TNT", "tnt", "filmes"),
  ch("tntnovelas", "TNT Novelas", "tntnovelas", "filmes"),
  ch("tntseries", "TNT Series", "tntseries", "filmes"),
  ch("universaltv", "Universal TV", "universaltv", "filmes"),
  ch("warnerchannel", "Warner Channel", "warnerchannel", "filmes"),
  // === NOTÍCIAS ===
  ch("band", "Band", "band", "noticias"),
  ch("bandnews", "Band News", "bandnews", "noticias"),
  ch("cnnbrasil", "CNN Brasil", "cnnbrasil", "noticias"),
  ch("globonews", "Globo News", "globonews", "noticias"),
  ch("record", "Record", "record", "noticias"),
  ch("sbt", "SBT", "sbt", "noticias"),
  // === ABERTOS ===
  ch("aparecida", "TV Aparecida", "tvaparecida", "abertos"),
  ch("cancaonova", "Can\xE7\xE3o Nova", "cancaonova", "abertos"),
  ch("cultura", "TV Cultura", "cultura", "abertos"),
  ch("globorj", "Globo RJ", "globorj", "abertos"),
  ch("globosp", "Globo SP", "globosp", "abertos"),
  ch("globomg", "Globo MG", "globosp", "abertos"),
  ch("globoam", "Globo AM", "globosp", "abertos"),
  ch("globors", "Globo RS", "globosp", "abertos"),
  ch("mtv", "MTV", "mtv", "abertos"),
  ch("multishow", "Multishow", "multishow", "abertos"),
  ch("viva", "VIVA", "viva", "abertos"),
  // === VARIEDADES ===
  ch("foodnetwork", "Food Network", "foodnetwork", "variedades"),
  ch("masterchef", "MasterChef", "masterchef", "variedades")
];

// src/lib/mcp/runtime.ts
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function backendUrl() {
  const value = runtimeEnv("SUPABASE_URL") ?? runtimeEnv("VITE_SUPABASE_URL");
  if (!value) throw new Error("Backend URL is not configured");
  return value.replace(/\/+$/, "");
}
var PUBLIC_SITE_URL = "https://lokifilms.qzz.io";

// src/lib/mcp/tools/list-live-channels.ts
var list_live_channels_default = defineTool({
  name: "list_live_channels",
  title: "Listar canais ao vivo",
  description: "Lista os canais ao vivo do LokiFilmes sem revelar os endere\xE7os das fontes de v\xEDdeo.",
  inputSchema: {
    category: z.string().trim().nullable().describe("ID da categoria; use null para listar todos os canais.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const validCategory = category && categories.some((item) => item.id === category) ? category : null;
    const matches = channels.filter((channel) => !validCategory || validCategory === "all" || channel.category === validCategory).map((channel) => ({ id: channel.id, name: channel.name, category: channel.category, logo: channel.logo }));
    return {
      content: [{ type: "text", text: `${matches.length} canal(is) dispon\xEDvel(is). Abra ${PUBLIC_SITE_URL}/tv para assistir.` }],
      structuredContent: {
        channels: matches,
        categories: categories.map(({ id, name }) => ({ id, name })),
        watch_url: `${PUBLIC_SITE_URL}/tv`
      }
    };
  }
});

// src/lib/mcp/tools/search-catalog.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^4.6.5";
var search_catalog_default = defineTool2({
  name: "search_catalog",
  title: "Buscar cat\xE1logo",
  description: "Busca filmes e s\xE9ries dispon\xEDveis no cat\xE1logo p\xFAblico do LokiFilmes.",
  inputSchema: {
    query: z2.string().trim().min(1).max(120).describe("T\xEDtulo do filme ou s\xE9rie."),
    media_type: z2.enum(["movie", "tv"]).nullable().describe("Filtre por filme ou s\xE9rie; use null para ambos."),
    limit: z2.number().int().min(1).max(20).nullable().describe("Quantidade de resultados; use null para 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, media_type, limit }, ctx) => {
    const endpoint = new URL(`${backendUrl()}/functions/v1/tmdb`);
    endpoint.searchParams.set("path", "/search/multi");
    endpoint.searchParams.set("language", "pt-BR");
    endpoint.searchParams.set("query", query);
    const response = await fetch(endpoint, { signal: ctx.signal });
    if (!response.ok) throw new ToolError(`A busca do cat\xE1logo falhou (${response.status}).`);
    const payload = await response.json();
    const results = (payload.results ?? []).filter((item) => item.media_type === "movie" || item.media_type === "tv").filter((item) => !media_type || item.media_type === media_type).slice(0, limit ?? 10).map((item) => {
      const type = item.media_type === "movie" ? "movie" : "serie";
      return {
        id: String(item.id ?? ""),
        title: item.title ?? item.name ?? "Sem t\xEDtulo",
        type,
        year: (item.release_date ?? item.first_air_date ?? "").slice(0, 4) || null,
        rating: typeof item.vote_average === "number" ? Math.round(item.vote_average * 10) / 10 : null,
        overview: item.overview || null,
        watch_url: item.id ? `${PUBLIC_SITE_URL}/watch/${type}/${item.id}` : null
      };
    });
    return {
      content: [{ type: "text", text: results.length ? `${results.length} resultado(s) encontrado(s).` : "Nenhum resultado encontrado." }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xfqocptliyukeypvylom";
var mcp_default = defineMcp({
  name: "lokifil1",
  title: "lokifil1",
  version: "0.1.0",
  instructions: "Ferramentas do LokiFilmes para buscar filmes e s\xE9ries e consultar a lista p\xFAblica de canais ao vivo.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_catalog_default, list_live_channels_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
